In [35]:
import pandas as pd
import numpy as np

In [36]:
emp = pd.DataFrame({
    'EmpID':[101,102,103,104,105,106],
    'Name':['A','B','C','D','E','F'],
    'Department':['HR','IT','IT','Finance','HR','Finance'],
    'Salary':[30000,50000,55000,60000,35000,65000],
    'Experience':[2,5,4,8,3,10]
})

print(emp)

   EmpID Name Department  Salary  Experience
0    101    A         HR   30000           2
1    102    B         IT   50000           5
2    103    C         IT   55000           4
3    104    D    Finance   60000           8
4    105    E         HR   35000           3
5    106    F    Finance   65000          10

In [37]:
emp.groupby('Department')['Salary'].mean()

Department
Finance    62500.0
HR         32500.0
IT         52500.0
Name: Salary, dtype: float64

In [38]:
emp.groupby('Department')['Salary'].max()

Department
Finance    65000
HR         35000
IT         55000
Name: Salary, dtype: int64

In [39]:
emp.groupby('Department')['Salary'].sum()

Department
Finance    125000
HR          65000
IT         105000
Name: Salary, dtype: int64

In [40]:
emp.groupby('Department')['EmpID'].count()

Department
Finance    2
HR         2
IT         2
Name: EmpID, dtype: int64

In [41]:
emp.groupby('Department')[['Salary','Experience']].mean()

             Salary  Experience
Department
Finance     62500.0         9.0
HR          32500.0         2.5
IT          52500.0         4.5

In [42]:
df1 = pd.DataFrame({
    'ID':[1,2,3,4],
    'Name':['A','B','C','D']
})

df2 = pd.DataFrame({
    'ID':[2,3,4,5],
    'City':['Pune','Mumbai','Delhi','Chennai']
})
print(df1)
print(df2)

   ID Name
0   1    A
1   2    B
2   3    C
3   4    D
   ID     City
0   2     Pune
1   3   Mumbai
2   4    Delhi
3   5  Chennai

In [43]:
pd.merge(df1, df2, on='ID', how='inner')

   ID Name    City
0   2    B    Pune
1   3    C  Mumbai
2   4    D   Delhi

In [44]:
pd.merge(df1, df2, on='ID', how='left')

   ID Name    City
0   1    A     NaN
1   2    B    Pune
2   3    C  Mumbai
3   4    D   Delhi

In [45]:
pd.merge(df1, df2, on='ID', how='right')

   ID Name     City
0   2    B     Pune
1   3    C   Mumbai
2   4    D    Delhi
3   5  NaN  Chennai

In [46]:
pd.merge(df1, df2, on='ID', how='outer')

   ID Name     City
0   1    A      NaN
1   2    B     Pune
2   3    C   Mumbai
3   4    D    Delhi
4   5  NaN  Chennai

In [47]:
pd.merge(df1, df2, on='ID', how='outer', indicator=True)\
.query("_merge != 'both'")

   ID Name     City      _merge
0   1    A      NaN   left_only
4   5  NaN  Chennai  right_only

In [48]:
pd.concat([df1, df2], axis=0)

   ID Name     City
0   1    A      NaN
1   2    B      NaN
2   3    C      NaN
3   4    D      NaN
0   2  NaN     Pune
1   3  NaN   Mumbai
2   4  NaN    Delhi
3   5  NaN  Chennai

In [49]:
pd.concat([df1, df2], axis=1)

   ID Name  ID     City
0   1    A   2     Pune
1   2    B   3   Mumbai
2   3    C   4    Delhi
3   4    D   5  Chennai

In [50]:
pd.concat([df1, df2], ignore_index=True)

   ID Name     City
0   1    A      NaN
1   2    B      NaN
2   3    C      NaN
3   4    D      NaN
4   2  NaN     Pune
5   3  NaN   Mumbai
6   4  NaN    Delhi
7   5  NaN  Chennai

In [51]:
pd.concat([df1, df2], keys=['First','Second'])

          ID Name     City
First  0   1    A      NaN
       1   2    B      NaN
       2   3    C      NaN
       3   4    D      NaN
Second 0   2  NaN     Pune
       1   3  NaN   Mumbai
       2   4  NaN    Delhi
       3   5  NaN  Chennai

In [52]:
sales = pd.DataFrame({
    'Region':['East','West','East','North','West'],
    'Product':['A','A','B','B','A'],
    'Sales':[1000,1500,2000,1200,1800]
})
print(sales)

  Region Product  Sales
0   East       A   1000
1   West       A   1500
2   East       B   2000
3  North       B   1200
4   West       A   1800

In [53]:
pd.pivot_table(sales,
               values='Sales',
               index='Region',
               aggfunc='sum')

        Sales
Region
East     3000
North    1200
West     3300

In [54]:
pd.pivot_table(sales,
               values='Sales',
               index='Region',
               columns='Product',
               aggfunc='sum')

Product       A       B
Region
East     1000.0  2000.0
North       NaN  1200.0
West     3300.0     NaN

In [55]:
pd.pivot_table(sales,
               values='Sales',
               index='Region',
               columns='Product',
               aggfunc='mean')

Product       A       B
Region
East     1000.0  2000.0
North       NaN  1200.0
West     1650.0     NaN

In [63]:
data = pd.DataFrame({
    'Date':['2025-01-01','2025-01-02','2025-01-03',
            '2025-01-04','2025-01-05'],
    'Sales':[100,200,150,300,250]
})

# Question 18
data['Date'] = pd.to_datetime(data['Date'])

print(data)

data['Date'] = pd.to_datetime(data['Date'])

data['Year'] = data['Date'].dt.year
data['Month'] = data['Date'].dt.month
data['Day'] = data['Date'].dt.day

print(data)

        Date  Sales
0 2025-01-01    100
1 2025-01-02    200
2 2025-01-03    150
3 2025-01-04    300
4 2025-01-05    250
        Date  Sales  Year  Month  Day
0 2025-01-01    100  2025      1    1
1 2025-01-02    200  2025      1    2
2 2025-01-03    150  2025      1    3
3 2025-01-04    300  2025      1    4
4 2025-01-05    250  2025      1    5

In [64]:
data.set_index('Date', inplace=True)

data['Rolling_Avg'] = data['Sales'].rolling(3).mean()

print(data)

            Sales  Year  Month  Day  Rolling_Avg
Date
2025-01-01    100  2025      1    1          NaN
2025-01-02    200  2025      1    2          NaN
2025-01-03    150  2025      1    3   150.000000
2025-01-04    300  2025      1    4   216.666667
2025-01-05    250  2025      1    5   233.333333

In [65]:
sales.groupby('Product')['Sales'].sum()

Product
A    4300
B    3200
Name: Sales, dtype: int64

In [66]:
sales.loc[sales.groupby('Region')['Sales'].idxmax()]

  Region Product  Sales
2   East       B   2000
3  North       B   1200
4   West       A   1800

In [67]:
customers = pd.DataFrame({
    'CustomerID':[1,2,3],
    'CustomerName':['A','B','C']
})

orders = pd.DataFrame({
    'CustomerID':[1,2,1],
    'OrderAmount':[500,1000,700]
})

pd.merge(customers, orders, on='CustomerID')

   CustomerID CustomerName  OrderAmount
0           1            A          500
1           1            A          700
2           2            B         1000

In [68]:
monthly = pd.DataFrame({
    'Month':['Jan','Jan','Feb','Feb'],
    'Product':['A','B','A','B'],
    'Sales':[1000,1200,1500,1800]
})

pd.pivot_table(monthly,
               values='Sales',
               index='Month',
               columns='Product',
               aggfunc='sum')

Product     A     B
Month
Feb      1500  1800
Jan      1000  1200

In [69]:
daily = pd.DataFrame({
    'Date':pd.date_range('2025-01-01', periods=10),
    'Sales':[100,200,150,300,250,400,350,450,500,550]
})

daily.set_index('Date', inplace=True)

daily.resample('W').sum()

            Sales
Date
2025-01-05   1000
2025-01-12   2250

In [70]:
daily['Cumulative_Sales'] = daily['Sales'].cumsum()

print(daily)

            Sales  Cumulative_Sales
Date
2025-01-01    100               100
2025-01-02    200               300
2025-01-03    150               450
2025-01-04    300               750
2025-01-05    250              1000
2025-01-06    400              1400
2025-01-07    350              1750
2025-01-08    450              2200
2025-01-09    500              2700
2025-01-10    550              3250

In [71]:
emp.groupby('Department')['Salary']\
.mean()\
.sort_values(ascending=False)\
.head(3)

Department
Finance    62500.0
IT         52500.0
HR         32500.0
Name: Salary, dtype: float64

In [72]:
dfA = pd.DataFrame({'ID':[1,2,3],'Name':['A','B','C']})
dfB = pd.DataFrame({'ID':[1,2,3],'City':['Pune','Mumbai','Delhi']})
dfC = pd.DataFrame({'ID':[1,2,3],'Age':[21,22,23]})

result = pd.merge(pd.merge(dfA, dfB, on='ID'),
                  dfC, on='ID')

print(result)

   ID Name    City  Age
0   1    A    Pune   21
1   2    B  Mumbai   22
2   3    C   Delhi   23

In [73]:
pd.pivot_table(
    sales,
    values='Sales',
    index='Region',
    columns='Product',
    aggfunc=['sum','mean','count']
)

            sum            mean         count
Product       A       B       A       B     A    B
Region
East     1000.0  2000.0  1000.0  2000.0   1.0  1.0
North       NaN  1200.0     NaN  1200.0   NaN  1.0
West     3300.0     NaN  1650.0     NaN   2.0  NaN